CREATE TABLE `osh_user_action_event`(
    `id`             BIGINT PRIMARY KEY NOT NULL COMMENT '主键ID',
    `user_id`        BIGINT COMMENT '用户id',
    `username`       VARCHAR(64) COMMENT '用户名',
    `role`           VARCHAR(32) COMMENT '角色',
    `module`         VARCHAR(64) COMMENT '模块名称',
    `method_name`    VARCHAR(128) COMMENT '方法名称',
    `action_type`    VARCHAR(32) COMMENT '操作类型',
    `resource_id`    VARCHAR(1024) COMMENT '资源ID集合，逗号分隔字符串',
    `resource_type`  VARCHAR(32) COMMENT '资源类型',
    `description`    VARCHAR(512) COMMENT '描述',
    `status`         VARCHAR(8) COMMENT '状态：0-失败，1-成功',
    `exception`      VARCHAR(1024) COMMENT '异常信息',
    `current_coin`   BIGINT COMMENT '当前金币',
    `current_point`  BIGINT COMMENT '当前积分',
    `happen_time`    DATETIME(6) COMMENT '发生时间',
    `create_time`    DATETIME COMMENT '创建时间',
    `create_by`      BIGINT COMMENT '创建人',
    `update_time`    DATETIME COMMENT '更新时间',
    `update_by`      BIGINT COMMENT '更新人',
    `delete_flag`    TINYINT DEFAULT 0 COMMENT '逻辑删除：0=未删除，1=已删除',
    KEY `idx_user_id` (`user_id`),
    KEY `idx_happen_time` (`happen_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_as_cs COMMENT='用户操作行为事件表';